#!/usr/bin/env bash

source ../helpers.sh
section "Configuring homebrew..."

BREWS="vim fasd direnv htop"

if [[ $(command -v brew) == "" ]]; then 
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
    brew install $BREWS &>/dev/null
    complete "Installed homebrew"
else
    echo "Updating and cleaning up Homebrew.."
    brew update &>/dev/null
    brew cleanup &>/dev/null
    brew upgrade $BREWS &>/dev/null
    complete "Updated homebrew"
fi
