#!/usr/bin/env bash

source ../helpers.sh
section "Configuring homebrew..."

BREWS="neovim fasd direnv htop thefuck fzf z"

LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)
$(brew --prefix)/opt/fzf/install --all

if [[ $(command -v brew) == "" ]]; then 
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
    brew install $BREWS &>/dev/null
    complete "Installed homebrew"
else
    echo "Updating and cleaning up Homebrew.."
    brew update &>/dev/null
    brew cleanup &>/dev/null
    brew upgrade $BREWS &>/dev/null
    complete "Updated homebrew"
fi
