#!/usr/bin/env bash
source ./brews.sh
source ../helpers.sh
section "Configuring homebrew..."

if [[ $(command -v brew) == "" ]]; then 
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
    brew install $BREWS &>/dev/null
    complete "Installed homebrew"
else
    echo "Updating and cleaning up Homebrew.."
    brew update
    brew cleanup
    brew install $BREWS 
    brew upgrade $BREWS 
    complete "Updated homebrew"
fi

$(brew --prefix)/opt/fzf/install --all
