#!/usr/bin/env bash

if [[ $(command -v brew) == "" ]]; then 
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
else
    brew update
    brew cleanup
fi
