#!/usr/bin/env bash

source ../helpers.sh

info "Uninstalling homebrew"

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" &>/dev/null

complete "Uninstalled homebrew"
