#!/usr/bin/env bash

curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh | LV_BRANCH='release-1.2/neovim-0.8' sh

rm -rf ~/.config/lvim/config.lua
ln -sf $PWD/config.lua ~/.config/lvim/config.lua
