#!/usr/bin/env bash

source ../helpers.sh
section "Configuring starship..."

brew install starship &>/dev/null || brew upgrade starship &>/dev/null

complete "Installed starship"

ln -sf $PWD/starship.toml ~/.config/starship.toml
complete "Linked starship config"

