#!/usr/bin/env bash

source ../helpers.sh
section "Configuring VS Code terminal helper..."

brew install --cask visual-studio-code

mkdir -p $HOME/.local/bin
ln -s $PWD/vscode $HOME/.local/bin/vscode

extensions=(achil.vscode-javascript-repl
ahmadalli.vscode-nginx-conf
alexkrechik.cucumberautocomplete
amatiasq.sort-imports
aws-scripting-guy.cform
azemoh.one-monokai
be5invis.vscode-custom-css
Bespohk.ducks-typescript-generator
bmewburn.vscode-intelephense-client
bungcip.better-toml
chrmarti.ssh
CodeStream.codestream
dbaeumer.vscode-eslint
denoland.vscode-deno
DotJoshJohnson.xml
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
fivepointseven.vscode-theme-onedark-spacegray
flowtype.flow-for-vscode
hbenl.vscode-test-explorer
joffreykern.markdown-toc
kavod-io.vscode-jest-test-adapter
magicstack.MagicPython
mattpocock.ts-error-translator
mgmcdermott.vscode-language-babel
ms-azuretools.vscode-docker
ms-playwright.playwright
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-vscode.azure-account
ms-vscode.test-adapter-converter
ms-vsliveshare.vsliveshare
naumovs.theme-oceanicnext
netcorext.uuid-generator
Orta.vscode-jest
PKief.material-icon-theme
plibither8.remove-comments
raynigon.nginx-formatter
redhat.vscode-commons
redhat.vscode-yaml
ryu1kn.partial-diff
scala-lang.scala
shanoor.vscode-nginx
stylelint.vscode-stylelint
Tyriar.lorem-ipsum
Tyriar.sort-lines
vscode-icons-team.vscode-icons
wayou.vscode-todo-highlight
wholroyd.jinja
wix.vscode-import-cost
wmaurer.change-case
yzane.markdown-pdf
zhuangtongfa.material-theme)

extensions_to_remove=(ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow)

complete "Configured VS Code"
