#!/usr/bin/env bash

ln -sf $PWD/.config/pypoetry ~/.config/pypoetry

echo "Install Python 3 and pip3"
brew install python3 || brew upgrade python3
python3 -m pip install --user --upgrade pip

echo "Installing Python 3 system wide packages"
pip3 install boto3 awscli ssh-docker poetry flake8

echo "Creating a virtualenv at ~/.venv"
python3 -m venv ~/.venv
