#!/usr/bin/env bash

source ../helpers.sh

section "Configuring Python..."

complete "Installed Python 3 and pip3"
brew install python3 &>/dev/null || brew upgrade python3 &>/dev/null
python3 -m pip install --user --upgrade pip &>/dev/null

ln -sf $PWD/.config/pypoetry ~/.config/pypoetry
complete "Set Poetry defaults"

ln -sf $PWD/.envrc $HOME/.envrc
complete "Set ~/ direnv .envrc"

pip3 install boto3 awscli ssh-docker flake8 autopep8 &>/dev/null
complete "Installed Python 3 system wide packages"

curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
complete "Installed Poetry"

python3 -m venv ~/.venv --symlinks --system-site-packages &>/dev/null
complete "Created default virtualenv at ~/.venv"
