#!/usr/bin/env bash

source "../utils.sh"

python_ini="python.ini"

# install required python versions
python_versions=($(extract_lines_from_section $python_ini "versions"))
for python_version in "${python_versions[@]}"; do
    pyenv install "$python_version"
done

pyenv global "${python_versions[0]}"

global_pypi_packages=($(extract_lines_from_section $python_ini "pypi_packages"))
for global_pypi_package in "${global_pypi_packages[@]}"; do
    pip install "$global_pypi_package"
done
