#!/usr/bin/env bash

echo "Resetting Finder defaults..."
defaults delete com.apple.finder DisableAllAnimations
defaults delete com.apple.finder NewWindowTarget
defaults delete com.apple.finder NewWindowTargetPath
defaults delete com.apple.finder ShowExternalHardDrivesOnDesktop
defaults delete com.apple.finder ShowHardDrivesOnDesktop
defaults delete com.apple.finder ShowMountedServersOnDesktop
defaults delete com.apple.finder ShowRemovableMediaOnDesktop
defaults delete com.apple.finder ShowStatusBar
defaults delete com.apple.finder ShowPathbar
defaults delete com.apple.finder AppleShowAllFiles
defaults delete com.apple.finder DSDontWriteNetworkStores
defaults delete NSGlobalDomain AppleShowAllExtensions

fillall Finder
