#!/usr/bin/env bash

source ../helpers.sh
section "Configuring zsh..."

ZROOTDIR=~/.zsh
ZSOURCEDIR=$ZROOTDIR/sources

mkdir -p $ZROOTDIR 
touch "$HOME/.zsh_history"
brew install zsh &>/dev/null || brew upgrade zsh &>/dev/null

complete "Installed zsh"

ln -sf $PWD/sources $ZSOURCEDIR
touch $ZSOURCEDIR/user.aliases.zsh
touch $ZSOURCEDIR/user.plugins.zsh
touch $ZSOURCEDIR/user.hooks.zsh
touch $ZSOURCEDIR/user.exports.zsh
ln -sf $PWD/.zshrc ~/.zshrc
complete "Linked zsh sources"

ZSH="$(which zsh)"
sudo cp $ZSH /bin/zsh &>/dev/null
chsh -s /bin/zsh &>/dev/null
complete "Set zsh as shell"
