#!/usr/bin/env bash

source ../helpers.sh
section "Configuring iterm2..."

brew cask install iterm2 &>/dev/null

complete "Installed iTerm2"

brew install TomAnthony/brews/itermocil &>/dev/null
complete "Installed iTermocil"

mkdir -p mkdir $HOME/.teamocil
ln -sf $HOME/.dotfiles/iterm2/profiles/com.googlecode.iterm2.plist $HOME/Library/Preferences
complete "Installed iTerm2 defaults"

info "To install custom themes navigate to $PWD/themes and load them into iTerm2"
